### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function find() on boolean

### ISSUE THREAD

**Issue by mjnewton** [lefoyer/larrymod#11]
A great plugin which seemingly works perfectly for me in all circumstances bar one - double-clicking messages *sometimes* returns a blank screen and the following syslog error:

`May 28 11:07:08 rugrat roundcube: PHP Fatal error:  Uncaught Error: Call to a member function find() on boolean in /home/mathew/NewtonNet/shtdocs/roundcube/plugins/larrymod/larrymod.php:180#012Stack trace:#012#0 /home/mathew/NewtonNet/shtdocs/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): larrymod->content_update(Array)#012#1 /home/mathew/NewtonNet/shtdocs/roundcube/program/include/rcmail_output_html.php(622): rcube_plugin_api->exec_hook('render_page', Array)#012#2 /home/mathew/NewtonNet/shtdocs/roundcube/program/include/rcmail_output_html.php(478): rcmail_output_html->parse('message', false)#012#3 /home/mathew/NewtonNet/shtdocs/roundcube/program/steps/mail/show.inc(176): rcmail_output_html->send('message', false)#012#4 /home/mathew/NewtonNet/shtdocs/roundcube/index.php(291): include_once('/home/mathew/Ne...')#012#5 {main}#012  thrown in /home/mathew/NewtonNet/shtdocs/roundcube/plugins/larrymod/larrymod.php on line 180` 

Running Roundcube v1.2.0. More than happy to provide further information if/as required.

Update: The issue only ever occurs if $rcmail_config['larrymod_headermini'] is set to true.

**Comment by lefoyer** [comment]
Update and check.

**Comment by mjnewton** [comment]
Perfect! Thank you Sergey!
