### ISSUE TITLE
Failure to display (very) large emails

### ISSUE THREAD

**Issue by mjnewton** [lefoyer/larrymod#12]
I have stumbled across an issue which appears to be triggered by very large emails:

Attempts to open a 5.6MB email (all content native in the body i.e. no attachments) with Larrymod enabled results in a completely blank screen being displayed.

Apache's logs show a 500 HTTP error and the Roundcube log shows:

> [26-Sep-2016 22:11:49 Europe/London] PHP Fatal error:  Uncaught Error: Call to a member function find() on boolean in /www-root/roundcube/plugins/larrymod/larrymod.php:180
> Stack trace:
> 0 /www-root/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): larrymod->content_update(Array)
> 1 www-root/roundcube/program/include/rcmail_output_html.php(622): rcube_plugin_api->exec_hook('render_page', Array)
> 2 /www-root/roundcube/program/include/rcmail_output_html.php(478): rcmail_output_html->parse('message', false)
> 3 /www-root/roundcube/program/steps/mail/show.inc(176): rcmail_output_html->send('message', false)
> 4 /www-root/roundcube/index.php(291): include_once('/www-root/round...')
> 5 {main}
>   thrown in /www-root/roundcube/plugins/larrymod/larrymod.php on line 180

Smaller emails (including ones that are around 4.5MB) work without any problems and disabling Larrymod results in all emails being displayed.

I am assuming it is the size of the emails that are the trigger but I could be wrong - it could just be coincidence.

Happy to provide further information if it helps you diagnose the issue.

**Comment by mjnewton** [comment]
I've just spotted that I reported a similar (same?) [issue](https://github.com/lefoyer/larrymod/issues/11) a few months ago and your update fixed it.

Looking through your [update](https://github.com/lefoyer/larrymod/commit/91bb1232479e3f98438e57ab22bf72b8183c4bff), and the increase to max_file_size specifically, increasing it from 6000000 to 60000000000 (just to experiment) gets things working again and the 5.6MB email displays fine.

Is there any drawback to setting this value to a massive value? Or perhaps it could just be set to something like 10000000 and that should suffice (until the next way-too-big email comes along!).

**Comment by lefoyer** [comment]
define('MAX_FILE_SIZE', 6000000);
in larrymod/lib/simple_html_dom.php

**Comment by lefoyer** [comment]
this need up memory_limit in php.ini.

**Comment by mjnewton** [comment]
Yes, my memory_limit is already high and so increasing MAX_FILE_SIZE has sorted it.

Thanks for such a quick response.
